### ISSUE TITLE
Plan for Iteration 0

### ISSUE THREAD

**Issue by zehuac2** [jackducham/mm26-visualizer#1]
The overall goal of iteration 0 is to build a minimal working visualizer for Mechmania 2020. Below are the tasks identified as needed to build a minimal working product.

# Phase 1

- [ ] Andrew Gao: add ECS related stuff
- [x] Peter: implement streaming functionalities #10 

## Optional

- [ ] Andrew Li & Aditya: research the following topics
  - [ ] UI
  - [ ] Amazon S3
  - [ ] Movement system
- [x] Map: implement a map controller that loads the map from a configuration file

# Phase 2

After Andrew Gao's ECS stuff is done, we can get started working on the basic systems and UIs of the game

- [ ] Movement system
- [ ] UI

No specific assignees are set due to the harsh reality of college.
